pyproject: bump `setuptools` requirement to 80.1.0
`py -3.9 run-tests.py` recently started failing on Windows with 75.6.0:

        $ time py -3.9 run-tests.py test-check-*
        Processing c:\users\matt\projects\mercurial\mercurial-devel
          Installing build dependencies: started
          Installing build dependencies: finished with status 'done'
          Getting requirements to build wheel: started
          Getting requirements to build wheel: finished with status 'error'
          error: subprocess-exited-with-error

          Getting requirements to build wheel did not run successfully.
          exit code: 1

          [87 lines of output]
          configuration error: `project.license` must be valid exactly by one definition (2 matches found):

              - keys:
                  'file': {type: string}
                required: ['file']
              - keys:
                  'text': {type: string}
                required: ['text']

        <snip>

            File "C:\hgdev\python39-x64\lib\site-packages\setuptools\config\pyprojecttoml.py", line 61, in validate
              raise ValueError(f"{error}\n{summary}") from None
          ValueError: invalid pyproject.toml config: `project.license`.
          configuration error: `project.license` must be valid exactly by one definition (2 matches found):

              - keys:
                  'file': {type: string}
                required: ['file']
              - keys:
                  'text': {type: string}
                required: ['text']

          [end of output]

No idea what the minimum required actually is, or why it suddenly changed from a
warning.

--HG--
extra : topic : cachestat-protocol