py3: fix sorting of obsolete markers when building bundle
Last item of marker tuple (parents) is either None or tuple. Comparison
thus fails on Python 3 with:

  TypeError: '<' not supported between instances of 'tuple' and 'NoneType'

Fixing this by coercing None to the empty tuple when sorting markers in
exchange._getbundleobsmarkerpart().