typing: add TypedDict definitions for the standard and WSGI environments
Pytype was seeing all of the possible types for the various values, and assuming
those types were possible for *any* value, and throwing a fit like this:

    mercurial/hgweb/wsgicgi_inner.py:46:8: error: in launch: No attribute 'lower' on BinaryIO [attribute-error]
      In Union[BinaryIO, bool, mercurial.hgweb.common.continuereader, mercurial.utils.procutil.WriteAllWrapper, mercurial.windows.winstdout, str, tuple[int, int]]

        if environ.get('HTTPS', 'off').lower() in ('on', '1', 'yes'):
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The definitions are copied from the places noted inline, but there's a module[1]
that used to live on GitHub, which has similar definitions, and more type
definitions, if we're allowed to copy MIT licensed code.  (Be careful, because
the "wsgi.output" variable defined there is NOT in the specs linked, so there
may be other issues.)

[1] https://git.sr.ht/~shabbyrobe/wsgitypes/tree/master/item/wsgitypes/__init__.py

--HG--
extra : absorb_source : a7a8e0e62a0a9dc8dc8d9d3d5fa7e6125ff7125c
extra : topic : typing-repo-alias