util: modernize `ctype` imports for Python 3 on Windows
I'm not sure why this popped up since the Windows CI system went down in July,
but the old imports worked on py 2.7, but no longer on py3.  This fixes:

        --- C:/Users/Matt/projects/mercurial/mercurial-devel/tests/test-clonebundles.t
        +++ C:/Users/Matt/projects/mercurial/mercurial-devel/tests/test-clonebundles.t.err
        @@ -885,11 +885,8 @@
           $ hg debug::clonebundle-manifest http://localhost:$HGPORT --raw
           http://localhost:$HGPORT1/gz-a.hg BUNDLESPEC=gzip-v2 REQUIREDRAM=12MB
           $ hg debug::clonebundle-manifest http://localhost:$HGPORT
        -    URL: http://localhost:$HGPORT1/gz-a.hg
        -      BUNDLESPEC: gzip-v2
        -      COMPRESSION: gzip
        -      VERSION: v2
        -      REQUIREDRAM: 12MB
        +  abort: cannot import name 'Structure' from 'ctypes.wintypes' (C:\hgdev\python39-x64\lib\ctypes\wintypes.py)
        +  [255]
           $ hg clone -U --debug --config ui.available-memory=16MB http://localhost:$HGPORT gzip-too-large
           using http://localhost:$HGPORT/
           sending capabilities command

        ERROR: test-clonebundles.t output changed

The `windll` import isn't recognized by pytype on Linux, so we still need to
disable the `import-error` here.

--HG--
branch : stable
extra : rebase_source : 5487ec2bf4a5610797542cd359b6369e70e78304
extra : topic : windows-test-fixes