error: use detailed exit code 10 for command errors
Command errors (unknown or ambiguous commands, or bad command
arguments or options) are handled in the `dispatch` module. Most other
errors are handled in the `scmutil` module. This patch therefore has
to duplicate a little bit of code from the `scmutil` module. It's just
a few lines, however, so it seems fine to me. It's a pretty common
category of errors, so it's important to have them respect
`ui.detailed-exit-code`.

Differential Revision: https://phab.mercurial-scm.org/D9777

--HG--
extra : rebase_source : 2f59764b20410d7653cdf1840ef2aeca42f6a2e9