largefiles: properly pass kwargs into url.open
The url.open function has acquired a lot of kwargs over the years.
When running `hg import http://example.com/hg/diff/1`, since at least
a708e1e4d7a8 in March, 2018, the calling sites for url.open try to
pass a `sendaccept` parameter that largefiles' override doesn't accept.

Currently that stack traces something like this:

  Traceback (most recent call last):
    File "/tmp/hgtests.sv744r5t/install/bin/hg", line 59, in <module>
      dispatch.run()
    File "/tmp/hgtests.sv744r5t/install/lib/python/mercurial/dispatch.py", line 143, in run
      status = dispatch(req)
    File "/tmp/hgtests.sv744r5t/install/lib/python/mercurial/dispatch.py", line 245, in dispatch
      status = _rundispatch(req)
    File "/tmp/hgtests.sv744r5t/install/lib/python/mercurial/dispatch.py", line 289, in _rundispatch
      ret = _runcatch(req) or 0
    File "/tmp/hgtests.sv744r5t/install/lib/python/mercurial/dispatch.py", line 465, in _runcatch
      return _callcatch(ui, _runcatchfunc)
    File "/tmp/hgtests.sv744r5t/install/lib/python/mercurial/dispatch.py", line 475, in _callcatch
      return scmutil.callcatch(ui, func)
    File "/tmp/hgtests.sv744r5t/install/lib/python/mercurial/scmutil.py", line 155, in callcatch
      return func()
    File "/tmp/hgtests.sv744r5t/install/lib/python/mercurial/dispatch.py", line 455, in _runcatchfunc
      return _dispatch(req)
    File "/tmp/hgtests.sv744r5t/install/lib/python/mercurial/dispatch.py", line 1259, in _dispatch
      lui, repo, cmd, fullargs, ui, options, d, cmdpats, cmdoptions
    File "/tmp/hgtests.sv744r5t/install/lib/python/mercurial/dispatch.py", line 913, in runcommand
      ret = _runcommand(ui, options, cmd, d)
    File "/tmp/hgtests.sv744r5t/install/lib/python/mercurial/dispatch.py", line 1270, in _runcommand
      return cmdfunc()
    File "/tmp/hgtests.sv744r5t/install/lib/python/mercurial/dispatch.py", line 1256, in <lambda>
      d = lambda: util.checksignature(func)(ui, *args, **strcmdopt)
    File "/tmp/hgtests.sv744r5t/install/lib/python/mercurial/util.py", line 1867, in check
      return func(*args, **kwargs)
    File "/tmp/hgtests.sv744r5t/install/lib/python/mercurial/commands.py", line 4184, in import_
      patchfile = hg.openpath(ui, patchurl, sendaccept=False)
    File "/tmp/hgtests.sv744r5t/install/lib/python/mercurial/hg.py", line 181, in openpath
      return url.open(ui, path, sendaccept=sendaccept)
  TypeError: openlargefile() got an unexpected keyword argument 'sendaccept'

So, just accept and pass along any kwargs of the overridden function.

--HG--
branch : stable