rust: fix non-utf8 char in requirements.rs
Apparently Phabricator detect `rust/hg-core/src/requirements.rs` file as non
utf8 ‽, and mark it as binary.  During application it ended up being non-utf8
and this made Rust (and as a result heptapod) very angry::

    error: couldn't read hg-core/src/requirements.rs: stream did not contain valid UTF-8
      --> hg-core/src/lib.rs:11:9
       |
    11 | pub mod requirements;
       |         ^^^^^^^^^^^^

    error: aborting due to previous error

    error: could not compile `hg-core`.

The after "fixing", the file content has no character matching the following
regexp:

  [^0-9-a-zA-Z /(|).,{}!\[\]:"&=>?_*-;<`'#]

So we should be fine, unless Phabricator does something funny again.

Differential Revision: https://phab.mercurial-scm.org/D9444