dirstate: fix panic when validating dirstate on write
We saw this crash with a message like this:

thread '<unnamed>' panicked at hg-core/src/dirstate/on_disk.rs:812:59:
range end index 18446744073709551615 out of range for slice of length 12

I believe this indicates that there's another bug or dirstate corruption that
this validation caught, since I think it wouldn't crash on valid inputs
(all "children" in this context are at level two or above, so they must
have a slash in their full paths, so "-1" for a slash should not overflow).

--HG--
branch : stable
extra : topic : fix-panic-when-validating-dirstate-before-write