git: add a missing reset_copy keyword argument to dirstate.set_tracked()
Since nothing else in hgext/git supports copies yet, the best I can do is avoid
TypeError: set_tracked() got an unexpected keyword argument 'reset_copy'.

--HG--
branch : stable
extra : rebase_source : 3c79514b296e92dae8c4a3a8330001b5190e3380
extra : topic : hgext-git