test-static-http.t: get kill actually working
- signal handlers take two arguments, not one
- add missing import sys

Before this patch, the

   $ kill $!

at the end of the test just caused a hidden traceback, sys.exit(0) was not
executed.

The swallowed traceback was:

  Traceback (most recent call last):
     File "dumb.py", line 10, in <module>
       run()
     File "dumb.py", line 7, in run
       httpd.serve_forever()
     File "/usr/lib/python2.6/SocketServer.py", line 224, in serve_forever
       r, w, e = select.select([self], [], [], poll_interval)
   TypeError: <lambda>() takes exactly 1 argument (2 given)