windows: avoid a bytes vs unicode crash reading passwords on py2
This broke in 5b3513177f2b.  Specifically, after typing in the password on py2,
it would crash with:

    TypeError: putwch() argument 1 must be cannot convert raw buffers, not str