pyoxidizer: disable using in-memory resources
It's possible that the errors are due to using an incompatible version of
PyOxidizer; unfortunately the README.md file in this directory says to fetch a
copy of PyOxidizer matching the commit in this pyoxidizer.bzl file, and yet the
pyoxidizer.bzl file does not actually have a commit mentioned in it.

By disabling in-memory modules, this appears to work on all platforms using the
current head version of PyOxidizer, so let's disable them for now.

Sample error (during `pyoxidizer build`):

```
error[PYOXIDIZER_PYTHON_EXECUTABLE]: adding PythonExtensionModule<name=hgext.fsmonitor.pywatchman.bser>

Caused by:
    extension module hgext.fsmonitor.pywatchman.bser cannot be loaded from memory but memory loading required
   --> ./pyoxidizer.bzl:140:5
    |
140 |     exe.add_python_resources(exe.pip_install(["--verbose", ROOT]))
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ add_python_resources()


error: adding PythonExtensionModule<name=hgext.fsmonitor.pywatchman.bser>

Caused by:
    extension module hgext.fsmonitor.pywatchman.bser cannot be loaded from memory but memory loading required
```

Differential Revision: https://phab.mercurial-scm.org/D11697