crecord: fix revert -ir '.^' crash caused by 3649c3f2cd
3649c3f2cd (revert: do not reverse hunks in interactive when REV is not
parent (issue5096)) changed the record "operation" for the text version but
missed the curses version. Without this patch, running
`hg revert -ir '.^' --config ui.interface=curses` would crash with:

  ProgrammingError: unexpected operation: apply

Differential Revision: https://phab.mercurial-scm.org/D1381