error: introduce StorageError
Errors in revlogs are often represented by RevlogError. It's fine
for revlogs to raise a revlog-specific exception. But in the context
of multiple storage backends, it doesn't make sense to be throwing or
catching an exception with "revlog" in its name when revlogs may not
even be in play.

This commit introduces a new generic StorageError type for representing
errors in the storage layer.

RevlogError is an instance of this type.

Interface documentation and tests referencing RevlogError has been
updated to specify StorageError should be used.

.. api::

   ``error.StorageError`` has been introduced to represent errors in
   storage. It should be used in place of ``error.RevlogError`` unless
   the error is known to come from a revlog.

Differential Revision: https://phab.mercurial-scm.org/D4654