py3: add b'' to some setup.py strings for Windows
These were things found trying to do `make PYTHON="py -3" local`.  The following
is dumped out, before dying while compiling the C extensions:

C:\Program Files\Python37\lib\site-packages\setuptools\dist.py:406: UserWarning:
  The version specified (b'4.7.1') is an invalid version, this may not work as
  expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440
  for more details.
  "details." % self.metadata.version
running build_py
byte-compiling .\mercurial\thirdparty\concurrent\futures\_base.py to _base.cpython-37.pyc
  File "mercurial\thirdparty\concurrent\futures\_base.py", line 416
    raise exception_type, self._exception, self._traceback
                        ^
SyntaxError: invalid syntax

# skip-blame since these are just converting to bytes literals