statprof: with Python 3.12, lineno is (more) often None
test-profile.t failed with errors like:
  TypeError: %d format: a real number is required, not NoneType

statprof.py already handled None values as -1 in some cases. Do the same in
more cases.

--HG--
branch : stable
extra : rebase_source : ae35945b1fa60360a4b1f8657d8642b33f44275d
extra : topic : mads-patches