py3: allow run-tests.py to run on Windows
This is now functional:

    HGMODULEPOLICY=py py -3 run-tests.py --local test-help.t --pure --view bcompare

However, on this machine without a C compiler, it tries to load cext anyway, and
blows up.  I haven't looked into why, other than to see that it does set the
environment variable.  When the test exits though, I see it can't find
killdaemons.py, get-with-headers.py, etc.

I have no idea why these changes are needed, given that it runs on Linux.  But
os.system() is insisting that it take a str, and subprocess.Popen() blows up
without str:

    Errored test-help.t: Traceback (most recent call last):
      File "run-tests.py", line 810, in run
        self.runTest()
      File "run-tests.py", line 858, in runTest
        ret, out = self._run(env)
      File "run-tests.py", line 1268, in _run
        exitcode, output = self._runcommand(cmd, env)
      File "run-tests.py", line 1141, in _runcommand
        env=env)
      File "C:\Program Files\Python37\lib\subprocess.py", line 756, in __init__
        restore_signals, start_new_session)
      File "C:\Program Files\Python37\lib\subprocess.py", line 1100, in _execute_child
        args = list2cmdline(args)
      File "C:\Program Files\Python37\lib\subprocess.py", line 511, in list2cmdline
        needquote = (" " in arg) or ("\t" in arg) or not arg
    TypeError: argument of type 'int' is not iterable

This is exactly how it crashes when trying to spin up a pager too.  I left one
instance of os.system() unchanged in _installhg(), because it doesn't get there.

--HG--
extra : amend_source : 72fff2f2168285c911f4f0ff01b2138b918db17a
extra : rebase_source : 4a16f32b0829805d0100b7d9f94c284c82d9db4f