error: remove shortening of node in error message
This strips the complete 20 bytes node which was not found. Having the the full
node in error message is important as it makes debugging easier.

If a short node is to be displayed, that should be done by callers.

Differential Revision: https://phab.mercurial-scm.org/D9994