error: convert `str` message to bytes
The C code set error message as `str`, so we need to handle them on the fly or
we will crash later down the road.

--HG--
extra : rebase_source : a9d2a8d41e80bd23aeb13a756f97937b6461d346
extra : topic : better-delta.format.pre