tests: restore the ability to run `black` on Windows
The hghave test for black silently stopped working with the change in
08fd76a553c9.  This was the output of what it was hitting when run in the test
environment:

    Traceback (most recent call last):\r (esc)
       File "c:\\users\\matt\\appdata\\local\\programs\\python\\python39\\lib\\runpy.py", line 197, in _run_module_as_main\r (esc)
         return _run_code(code, main_globals, None,\r (esc)
       File "c:\\users\\matt\\appdata\\local\\programs\\python\\python39\\lib\\runpy.py", line 87, in _run_code\r (esc)
         exec(code, run_globals)\r (esc)
       File "c:\\Users\\Matt\\AppData\\Roaming\\Python\\Python39\\Scripts\\black.exe\\__main__.py", line 4, in <module>\r (esc)
       File "C:\\Users\\Matt\\AppData\\Roaming\\Python\\Python39\\site-packages\\black\\__init__.py", line 70, in <module>\r (esc)
         CACHE_DIR = Path(user_cache_dir("black", version=__version__))\r (esc)
       File "C:\\Users\\Matt\\AppData\\Roaming\\Python\\Python39\\site-packages\\appdirs.py", line 293, in user_cache_dir\r (esc)
         path = os.path.normpath(_get_win_folder("CSIDL_LOCAL_APPDATA"))\r (esc)
       File "C:\\Users\\Matt\\AppData\\Roaming\\Python\\Python39\\site-packages\\appdirs.py", line 481, in _get_win_folder_with_pywin32\r (esc)
         dir = shell.SHGetFolderPath(0, getattr(shellcon, csidl_name), 0, 0)\r (esc)
     pywintypes.com_error: (-2147024893, '$ENOTDIR$.', None, None)\r (esc)
     [1]

Differential Revision: https://phab.mercurial-scm.org/D10310