tests: fix glob pattern for dynamic timer alignment
The number of space characters varies depending on the number of digits of the
timer, making some tests fail on slow machines in an unintended way:

```diff
--- /build/mercurial-6.1/tests/test-merge-halt.t
+++ /build/mercurial-6.1/tests/test-merge-halt.t.err
@@ -210,6 +210,6 @@
   merge halted after failed merge (see hg resolve)
   [240]
   $ hg shelve --list
-  default         (* ago)    changes to: foo (glob)
+  default         (11s ago)   changes to: foo
   $ hg unshelve --abort
   unshelve of 'default' aborted
ERROR: test-merge-halt.t output changed
```

Differential Revision: https://phab.mercurial-scm.org/D12381