interfaces: add a few missing repository attributes
The private attribute is unfortunate, but used by the upgrade engine.  This
fixes the following, when `IRepo.unfiltered()` gets a return type:

        /home/mharbison/projects/mercurial/mercurial-devel/mercurial/verify.py:644:48:
            error: in _verify_dirstate: No attribute 'is_narrow' on mercurial.interfaces.repository.IRepo [attribute-error]

                narrow_matcher = repo.narrowmatch() if repo.is_narrow else None
                                                       ~~~~~~~~~~~~~~
        [...]
        /home/mharbison/projects/mercurial/mercurial-devel/mercurial/upgrade_utils/engine.py:544:21:
            error: in upgrade: No attribute '_rootstore' on mercurial.interfaces.repository.imanifestlog [attribute-error]

                        tr, unfi.manifestlog._rootstore._revlog, force=True
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~

        /home/mharbison/projects/mercurial/mercurial-devel/mercurial/upgrade_utils/engine.py:565:30:
            error: in upgrade: No attribute '_rootstore' on mercurial.interfaces.repository.imanifestlog [attribute-error]

                        tr, srcrepo, unfi.manifestlog._rootstore._revlog
                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~

--HG--
extra : rebase_source : bdfe971bdfaa13a2bbdf1d828fbee396dd7596e4
extra : topic : typing-callable3