interfaces: add private lock methods used by clonebundles to IRepo protocol
When `@localrepository.unfilteredmethod` is fixed to preserve the underlying
method signature, pytype starts complaining about the clonebundles extension:

        /home/mharbison/projects/mercurial/mercurial-devel/hgext/clonebundles.py:995:17:
            error: in clonebundles_lock: No attribute '_currentlock' on autobundlesrepo [attribute-error]

                    l = self._currentlock(self._cb_lock_ref)
                        ~~~~~~~~~~~~~~~~~

        /home/mharbison/projects/mercurial/mercurial-devel/hgext/clonebundles.py:1000:17:
            error: in clonebundles_lock: No attribute '_lock' on autobundlesrepo [attribute-error]

                    l = self._lock(
                        ~~~~~~~~~~

It's possible for `self._cb_lock_ref` to be None for the first location, which
is why it needed to be fixed in the previous commit.

--HG--
extra : _rewrite_noise : 51078cd5288d5b70e87e7148aa70d34b8c3ccb76
extra : amend_source : a56706ee57ada9692b05472f5724493f31a0fb54
extra : topic : typing-callable2