hghave: make the description for "clang-format" ascii
test-fix-clang-format.t suddenly started failing on Windows by wiping the whole
file content, and replacing with an error:

      $TESTTMP.sh: $TESTTMP.sh: cannot execute binary file

Odd, because I don't have `clang-format` installed, so the test should be
skipped.  The problem started with 73cf8b56c2f5, and I noticed that running
`hghave` manually resulted in a `SyntaxError` (so I can't see how this isn't
broken everywhere, but maybe it's because I'm using py3.9 on Windows):

    $ py hghave --list
    Traceback (most recent call last):
      File "hghave", line 8, in <module>
        import hghave
      File "c:\Users\Matt\hg\tests\hghave.py", line 627
    SyntaxError: Non-ASCII character '\xe2' in file c:\Users\Matt\hg\tests\hghave.py on line 627, but no encoding declared;
        see http://python.org/dev/peps/pep-0263/ for details