packaging: rename hgrc.d to defaultrc for Windows config files next to the exe
The code and the help still says that it will read hgrc.d next to the
executable.  But this directory needs to exist to read the resource based config
files.  Otherwise even `hg version` errors out:

    $ /c/Program\ Files/Mercurial/hg.exe version
    Traceback (most recent call last):
      File "hg", line 43, in <module>
      File "mercurial\dispatch.pyc", line 110, in run
      File "mercurial\dispatch.pyc", line 226, in dispatch
      File "mercurial\ui.pyc", line 308, in load
      File "mercurial\rcutil.pyc", line 99, in rccomponents
      File "mercurial\rcutil.pyc", line 69, in default_rc_resources
      File "mercurial\utils\resourceutil.pyc", line 84, in contents
    WindowsError: [Error 3] The system cannot find the path specified: 'c:\\Program Files\\mercurial\\defaultrc\\*.*'

Differential Revision: https://phab.mercurial-scm.org/D7981

--HG--
branch : stable