zeroconf: fix traceback under py3
hg serve under py3 caused
struct.error: char format requires a bytes object of length 1

<pulkit25> ah, I think that should be `pycompat.bytechr` instead of chr

--HG--
branch : stable
extra : fix_source : ac9339b55adf7c52cae450f66ab911d7f97b31bf