test-check-py3-compat: exclude thirdparty and cffi which are known to fail
Otherwise the following errors would be spilled out:

  mercurial/cffi/bdiff.py: error importing: <ImportError> cannot import
  name '_bdiff' (error at bdiff.py:*)
  mercurial/cffi/bdiffbuild.py: error importing: <ModuleNotFoundError> No
  module named 'cffi' (error at bdiffbuild.py:*)
  mercurial/cffi/mpatch.py: error importing: <ImportError> cannot import
  name '_mpatch' (error at mpatch.py:*)
  mercurial/cffi/mpatchbuild.py: error importing: <ModuleNotFoundError> No
  module named 'cffi' (error at mpatchbuild.py:*)
  mercurial/cffi/osutilbuild.py: error importing: <ModuleNotFoundError> No
  module named 'cffi' (error at osutilbuild.py:*)
  mercurial/thirdparty/concurrent/futures/_base.py: invalid syntax: invalid
  syntax (<unknown>, line *)
  mercurial/thirdparty/concurrent/futures/process.py: error importing:
  <SyntaxError> invalid syntax (_base.py, line 416) (error at __init__.py:*)
  mercurial/thirdparty/concurrent/futures/thread.py: error importing:
  <SyntaxError> invalid syntax (_base.py, line 416) (error at __init__.py:*)
  mercurial/thirdparty/zope/interface/_flatten.py: error importing:
  <ImportError> cannot import name 'Declaration' (error at _flatten.py:*)

Some of them can be suppressed by building cffi modules for example, but
I don't think it's worth keeping these modules covered by the compatibility
checker.