hgdemandimport: add collections.abc to the ignore list because Python 3.13 rc3
It worked in Python 3.13 rc2, but something changed for rc3.

Now, when i18n.py imports typing and it touches collections.abc.Hashable , we
get:

  ValueError: module object for collections.abc substituted in sys.modules during a lazy load

This seems to be a general problem, released in the final Python 3.13 . I have
not analyzed the problem in details.

We *could* work around the problem by disabling demand import of typing. But
that would effectively disable demand import of collections.abc too. Instead,
just disable demand import for collections.abc .

--HG--
branch : stable
extra : rebase_source : 7476beb09f498b77626a7e57f16a510e706e9f28
extra : topic : 3.13-abc